name: Revolve
favicon: null
layout_spectrum: 0.10093382420018315
typography_spectrum: 0.7208480436820537
title: revolve
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171717'
    - '#10479b'
    - '#f7f9fc'
    - '#595b5e'
    - '#9fa1a4'
  brandStrength: 0.875
  lightness: 0.20999671868048608
  saturation: 0.3608540929853916
  rhythmicContrast: 0.00015636533498764038
purpose: []
